# Generated by Django 6.0.5 on 2026-05-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='face_count',
            field=models.IntegerField(default=0),
        ),
    ]
