# Generated by Django 6.0.5 on 2026-05-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceembedding',
            name='face_index',
            field=models.IntegerField(default=0),
        ),
    ]
