# Generated by Django 6.0.5 on 2026-05-20 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('recognition', '0002_faceembedding_face_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceembedding',
            name='face_index',
        ),
        migrations.RemoveField(
            model_name='faceembedding',
            name='image',
        ),
        migrations.CreateModel(
            name='DetectedFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_image', models.ImageField(upload_to='faces/')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='images.image')),
            ],
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='face',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='recognition.detectedface'),
            preserve_default=False,
        ),
    ]
