# Generated by Django 6.0.5 on 2026-05-20 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0003_remove_faceembedding_face_index_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectedface',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='faceembedding',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='detectedface',
            name='detection_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='model_name',
            field=models.CharField(default='ArcFace', max_length=64),
        ),
        migrations.AlterField(
            model_name='detectedface',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='faces/'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='face',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_record', to='recognition.detectedface'),
        ),
    ]
