# Generated by Django 6.0.5 on 2026-05-20 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0004_alter_detectedface_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectedface',
            options={},
        ),
        migrations.AlterModelOptions(
            name='faceembedding',
            options={},
        ),
        migrations.RemoveField(
            model_name='detectedface',
            name='detection_confidence',
        ),
        migrations.RemoveField(
            model_name='faceembedding',
            name='model_name',
        ),
        migrations.AlterField(
            model_name='detectedface',
            name='face_image',
            field=models.ImageField(default=101, upload_to='faces/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='face',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='recognition.detectedface'),
        ),
    ]
